CLEANUP = rm -rf
CHECKER_OUTPUT_DIR = ../../checker-output

#We try to detect the OS we are running on, and adjust commands as needed
ifeq ($(OS),Windows_NT)
  ifeq ($(shell uname -s),) # not in a bash-like shell
	CLEANUP = rmdir
  endif
endif


all: clean setup compile test_1 test_2 test_3 test_4 check

clean:
# TODO: Delete all output files that will be generated by the build process
	$(CLEANUP) $(CHECKER_OUTPUT_DIR)
	rm -rf build

setup:
# TODO: Create actual output directory
	mkdir build
	meson setup $(CHECKER_OUTPUT_DIR)

compile:
	meson compile -C $(CHECKER_OUTPUT_DIR)

.PHONY: test_1
test_1:
	gcc -o build/test_1 tests/test_1/main_1.c ../../src/fizz_buzz.c 
	build/test_1 > ../../checker-output/actual_output_1.txt 2>&1

.PHONY: test_2
test_2:
	gcc -o build/test_2 tests/test_2/main_2.c ../../src/fizz_buzz.c 
	build/test_2 > ../../checker-output/actual_output_2.txt 2>&1

.PHONY: test_3
test_3:
	gcc -o build/test_3 tests/test_3/main_3.c ../../src/fizz_buzz.c 
	build/test_3 > ../../checker-output/actual_output_3.txt 2>&1

.PHONY: test_4
test_4:
	gcc -o build/test_4 tests/test_4/main_4.c ../../src/fizz_buzz.c 
	build/test_4 > ../../checker-output/actual_output_4.txt 2>&1

check:
	meson test -C $(CHECKER_OUTPUT_DIR) --print-errorlogs -v